import type { Metadata } from "next";
import "./globals.css";
import PageUpButton from "./components/main/PageUpButton";
import EmblaCarousel from "./components/AdoptEmblaCarousel";


export const metadata: Metadata = {
  title: "GoPet",
  description: "Generated by Stella An",
};

export default function RootLayout({ children }: { children: React.ReactNode}) {
  return (
    <html lang="en">
      <body>
          {children}
          <PageUpButton />
      </body>
    </html>
  );
}
